version: '3'
services:
  app:
    build: ./Dockerfiles/app
    image: php7.2-apache:dbm
    stdin_open: true
    tty: true
    volumes:
      - ~/Projects/uplexis_crawler2/app:/var/www/app
    ports:
      - "80:80"
    command:
      - /var/www/entrypoint/entrypoint.sh
    links:
      - db
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"