version: '3'
services:
  app:
    build: ./Dockerfiles/app
    image: php7.2-apache
    stdin_open: true
    tty: true
    volumes:
      - ~/Projects/uplexis/app:/var/www/app
    ports:
      - "80:80"
    command:
      - /var/www/entrypoint/entrypoint.sh
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: uplexis
    ports:
      - "3306:3306"